name: Cucumber + Cypress Tests

on:
  push:
    branches:
      - main
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install
      
      - name: Setup Java for Allure
        if: always()
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 25

      - name: Install Allure CLI + allure-cypress
        if: always()
        run: npm install -g allure-commandline allure-cypress
        
      - name: Check imported files
        run: |
          echo "Checking e2e.js content..."
          cat cypress/support/e2e.js || echo "No e2e.js found"
          
      - name: Run Cypress tests
        run: npx cypress run --browser chrome --headless
        


      - name: Generate Allure Report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
